config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :folios

  resources :folio_pages, path: 'folios/pages' do
    post 'add_row', to: 'add_row'
    post 'merge_row_column', to: 'merge_row_column'
    get 'create_caption', to: 'create_caption'
    get 'create_image', to: 'create_image'
    get 'delete_content', to: 'delete_content'
  end

  resources :captions, path: 'folios/pages/captions', only: [:edit, :update]
  resources :images, path: 'folios/pages/images', only: [:edit, :update]
  resources :folio_comments, path: 'folios/comments', only: [:create]

  resources :users, path: 'users', only: [:edit, :update, :show]

  root 'landing#index'
end

app/models/folio_page.rb
class FolioPage < ApplicationRecord
  belongs_to :folio
  has_many :folio_page_rows
  has_many :folio_page_row_columns

  validates :title, presence: true, length: { minimum: 1 }
end

app/controllers/folio_pages_controller.rb
class FolioPagesController < ApplicationController
  def index

  end

  def new
    needs_authentication
    @folio_page = FolioPage.new(folio_id: params[:folio_id])
  end

  def create
    needs_authentication
    @folio_page = FolioPage.new(folio_page_params.merge(folio:
      Folio.find(params[:folio_id])))

    if @folio_page.save
      redirect_to @folio_page
    else
      render 'new'
    end
  end

  def show
    @folio_page = FolioPage.find(params[:id])
    @folio = @folio_page.folio
    @rows = @folio_page.folio_page_rows
    raise 'Folio Page doesn\'t exist' if @folio.nil?
  end

  def add_row
    @folio = Folio.find(params[:folio_id])
    @folio_page = FolioPage.find(params[:folio_page_id])
    @folio_page_row = FolioPageRow.new(add_row_params.merge(folio:
      @folio, folio_page: @folio_page))

    needs_authentication
    needs_own_folio

    if @folio_page_row.save
      redirect_to @folio_page
    else
      render json: {status: 'error', error: @folio_page.errors.full_messages}
    end
  end

  def merge_row_column
    @folio = Folio.find(params[:folio_id])
    @folio_page = FolioPage.find(params[:folio_page_id])

    needs_authentication
    needs_own_folio

    folio_page_row = FolioPageRow.find(params[:folio_page_row_id])
    col_1 = folio_page_row.folio_page_row_columns.
      find(params[:folio_page_row_column_id])

    col_2 = folio_page_row.folio_page_row_columns.where('column_order > ?',
      col_1.column_order).first
    raise 'Adjacent column doesn\'t exist' if col_2.nil?

    col_1.column_width += col_2.column_width
    col_1.save
    col_2.destroy

    redirect_to @folio_page
  end

  def create_caption
    @folio_page = FolioPage.find(params[:folio_page_id])
    @folio = @folio_page.folio

    needs_authentication
    needs_own_folio

    col = FolioPageRowColumn.find(params[:at].to_i)
    fail 'no column with id' if col.nil?
    new_caption = Caption.new(user_id: @folio.user_id,
      folio_page_id: @folio_page.id)
    new_caption.save!

    col.caption_id = new_caption.id
    col.save!

    redirect_to(edit_caption_path(new_caption))
  end

  def create_image
    @folio_page = FolioPage.find(params[:folio_page_id])
    @folio = @folio_page.folio

    needs_authentication
    needs_own_folio

    col = FolioPageRowColumn.find(params[:at].to_i)
    fail 'no column with id' if col.nil?
    new_image = Image.new(user_id: @folio.user_id,
      folio_page_id: @folio_page.id)
    new_image.save!

    col.image_id = new_image.id
    col.save!

    redirect_to(edit_image_path(new_image))
  end

  def delete_content
    @folio_page = FolioPage.find(params[:folio_page_id])
    @folio = @folio_page.folio

    needs_authentication
    needs_own_folio

    col = FolioPageRowColumn.find(params[:at].to_i)
    col.image.destroy unless col.image.nil?
    col.caption.destroy unless col.caption.nil?

    redirect_to(@folio_page)
  end

  private
  def folio_page_params
    params.require(:folio_page).permit(:title, :folio_id)
  end

  def merge_row_column_params
    params.permit(:folio_id, :folio_page_id, :folio_page_row_id,
      :folio_page_row_column_id)
  end

  def add_row_params
    params.permit(:folio_id, :folio_page_id, :row_order)
  end
end

app/helpers/folio_pages_helper.rb
module FolioPagesHelper
end

app/views/folio_pages/_form.html.erb
<%= form_for @folio_page do |f| %>
  <% if @folio_page.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p><b>Whoops.</b> Looks like there were some issues with your request</p>
      <ul>
        <% @folio_page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= f.submit submit_text, class: 'btn btn-primary btn-lg btn-block' %>
  </div>

  <%= hidden_field_tag :folio_id, @folio_page.folio_id %>
<% end %>

app/views/folio_pages/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="page-header">
      <h1>Create a Folio Page</h1>
    </div>

    <%= render 'form', submit_text: 'Create Folio' %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/folio_pages/show.html.erb
<div class="row">
  <div class="col-md-12 folio-page-tab-bar">
    <ul class="nav nav-tabs">
      <% @folio.folio_pages.order(:page_order).each do |folio_page| %>
      <li role="presentation" <% if folio_page == @folio_page %>class="active"<%end%>>
        <%= link_to folio_page.title, folio_page %>
      </li>
      <% end %>
      <% if current_user_owns_folio? %>
        <li role="presentation"><%= link_to '+', new_folio_page_path(folio_id: @folio.id) %></li>
      <% end %>
      <% if current_user_owns_folio? %>
      <a class="btn btn-primary" style="float: right;" id="editModeBtn" href="javascript:toggleEditMode()">Edit Mode (on)</a>
      <% end %>
    </ul>
  </div>
</div>

<% @rows.each do |row| %>
  <div class="row">
    <% row.folio_page_row_columns.each do |col| %>
      <div class="col-md-<%= col.column_width * 3 %>">
        <% if !col.caption.nil? %>
          <%= render '/captions/caption', caption: col.caption %>
        <% elsif !col.image.nil? && !col.image.image.file.nil? %>
          <%= render '/images/image', image: col.image %>
        <% end %>
        <% if current_user_owns_folio? %>
          <div class="toolbox">
            <% if col.caption.nil? && col.image.nil? %>
              <div class="well" style="text-align: center;">
                <div style="display: inline-block;">
                  <div class="btn-group btn-group-xs" role="group" aria-label="...">
                    <%= link_to 'Caption', folio_page_create_caption_path(@folio_page, at: col.id), class: 'btn btn-default' %>
                    <%= link_to 'Image', folio_page_create_image_path(@folio_page, at: col.id), class: 'btn btn-default' %>
                    <button type="button" class="btn btn-default" onclick="mergeRight(<%= row[:id] %>, <%= col[:id] %>)">Merge Right</button>
                  </div>
                </div>
              </div>
            <% else %>
              <div class="well well-sm">
                <div style="text-align: center;">
                  <span class="badge"><%= !col.caption.nil? ? 'Caption' : 'Image' %></span>
                  <div class="btn-group btn-group-xs" role="group" aria-label="...">
                    <% unless col.caption.nil? %>
                      <%= link_to 'Edit', edit_caption_path(col.caption), class: 'btn btn-default' %>
                    <% else %>
                      <%= link_to 'Edit', edit_image_path(col.image), class: 'btn btn-default' %>
                    <% end %>
                    <%= link_to 'Delete', folio_page_delete_content_path(@folio_page, at: col.id), class: 'btn btn-default' %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

<% if current_user_owns_folio? %>
  <div class="row toolbox">
    <div class="col-md-12">
      <%= form_for :folio_page_row, url: folio_page_add_row_path(@folio_page) do |f| %>
        <%= hidden_field_tag :folio_id, @folio.id %>
        <%= hidden_field_tag :folio_page_id, @folio_page.id %>
        <%= hidden_field_tag :row_order, @rows.length %>
        <%= f.submit 'Add Row', class: 'btn btn-primary btn-lg btn-block ' %>
      <% end %>
    </div>
  </div>

  <%= form_for :folio_page_row, html: {id: 'merge_folio'}, url: folio_page_merge_row_column_path(@folio_page) do |f| %>
  <%= hidden_field_tag :folio_id, @folio.id, id: 'merge_folio_id' %>
  <%= hidden_field_tag :folio_page_id, @folio_page.id, id: 'merge_folio_page_id' %>
  <%= hidden_field_tag :folio_page_row_id, 0, id: 'merge_folio_page_row_id' %>
  <%= hidden_field_tag :folio_page_row_column_id, 0, id: 'merge_folio_page_row_column_id' %>
  <% end %>

  <script>
    var editMode = true;

    function mergeRight(row_id, id) {
      $('#merge_folio_page_row_column_id')[0].value = id;
      $('#merge_folio_page_row_id')[0].value = row_id;

      $('#merge_folio')[0].submit();
    }

    function toggleEditMode() {
      editMode = !editMode;

      if(editMode) {
        $('.toolbox').show();
      } else {
        $('.toolbox').hide();
      }

      updateEditModeBtn();
    }

    function updateEditModeBtn() {
      if(editMode) {
        $('#editModeBtn')[0].className = 'btn btn-primary';
        $('#editModeBtn')[0].innerHTML = 'Edit Mode (on)';
      } else {
        $('#editModeBtn')[0].className = 'btn btn-default';
        $('#editModeBtn')[0].innerHTML = 'Edit Mode (off)';
      }
    }

    updateEditModeBtn();
  </script>
<% end %>