config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resources :folios

  resources :folio_pages, path: 'folios/pages' do
    post 'add_row', to: 'add_row'
    post 'merge_row_column', to: 'merge_row_column'
    get 'create_caption', to: 'create_caption'
    get 'create_image', to: 'create_image'
    get 'delete_content', to: 'delete_content'
  end

  resources :captions, path: 'folios/pages/captions', only: [:edit, :update]
  resources :images, path: 'folios/pages/images', only: [:edit, :update]
  resources :folio_comments, path: 'folios/comments', only: [:create]

  resources :users, path: 'users', only: [:edit, :update, :show]

  root 'landing#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caption.rb
class Caption < ApplicationRecord
  belongs_to :user
  belongs_to :folio_page
end

app/models/folio.rb
class Folio < ApplicationRecord
  belongs_to :user
  has_many :folio_pages
  has_many :folio_page_rows
  has_many :folio_comments

  validates :name, presence: true, length: { minimum: 5 }
end

app/models/folio_comment.rb
class FolioComment < ApplicationRecord
  belongs_to :folio
  belongs_to :user
end

app/models/folio_page.rb
class FolioPage < ApplicationRecord
  belongs_to :folio
  has_many :folio_page_rows
  has_many :folio_page_row_columns

  validates :title, presence: true, length: { minimum: 1 }
end

app/models/folio_page_row.rb
class FolioPageRow < ApplicationRecord
  belongs_to :folio_page
  belongs_to :folio

  has_many :folio_page_row_columns

  after_create :make_cols

  def make_cols
    4.times do |i|
      folio_page_row_columns.create(folio_id: self.folio_id,
        folio_page_id: self.folio_page_id, column_width: 1, column_order: i)
    end
  end
end

app/models/folio_page_row_column.rb
class FolioPageRowColumn < ApplicationRecord
  belongs_to :folio_page_row
  belongs_to :folio_page
  belongs_to :folio

  belongs_to :caption, optional: true
  belongs_to :image, optional: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  belongs_to :folio_page

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  has_many :folios, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)

      # Set the image from Google if the user has one
      if auth.info.image
        user.image = auth.info.image
      end

      user.save!
    end
  end
end

app/controllers/folios_controller.rb
class FoliosController < ApplicationController
  def index
    # TODO pagination
    @folios = Folio.all
  end

  def new
    needs_authentication
    @folio = Folio.new
  end

  def edit
    needs_authentication
    @folio = Folio.find(params[:id])
    rause 'Folio doesn\'t exist' if @folio.nil?
    raise 'You don\'t have permission to edit this folio' \
      if current_user != @folio.user
  end

  def create
    needs_authentication
    @folio = Folio.new(folio_params.merge(user_id: current_user.id))

    if @folio.save
      redirect_to @folio
    else
      render 'new'
    end
  end

  def update
    needs_authentication
    @folio = Folio.find(params[:id])
    raise 'Folio doesn\'t exist' if @folio.nil?
    raise 'You don\'t have permission to edit this folio' \
      if current_user != @folio.user

    if @folio.update(folio_params)
      redirect_to @folio
    else
      render 'edit'
    end
  end

  def show
    @folio = Folio.find(params[:id])
    raise 'Folio doesn\'t exist' if @folio.nil?
    @first_folio_page = @folio.folio_pages.order(:page_order).first
  end

  private
  def folio_params
    params.require(:folio).permit(:name, :description, :tags)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def edit
    @image = Image.find(params[:id])
  end

  def update
    needs_authentication
    @image = Image.find(params[:id])
    raise 'Image doesn\'t exist' if @image.nil?
    raise 'You don\'t have permission to edit this folio' \
      if current_user != @image.user

    if @image.update(image_params)
      redirect_to(@image.folio_page)
    else
      render 'edit'
    end
  end

  private
  def image_params
    params.require(:image).permit(:image)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    raise 'User doesn\'t exist' if @user.nil?
  end

  def edit
    needs_authentication
    @user = User.find(params[:id])
    raise 'Folio doesn\'t exist' if @user.nil?
    raise 'You don\'t have permission to edit this user' \
      if current_user != @user
  end

  def update
    needs_authentication
    @user = User.find(params[:id])
    raise 'Folio doesn\'t exist' if @user.nil?
    raise 'You don\'t have permission to edit this user' \
      if current_user != @user

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true,
      escape_html:     true
    }

    extensions = {
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/captions_helper.rb
module CaptionsHelper
end

app/helpers/folio_comments_helper.rb
module FolioCommentsHelper
end

app/helpers/folio_helper.rb
module FolioHelper
end

app/helpers/folio_page_rows_helper.rb
module FolioPageRowsHelper
end

app/helpers/folio_pages_helper.rb
module FolioPagesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/folio/new.html.erb
<div class="page-header">
  <h1>Create a Folio</h1>
</div>

<%= form_for :folio do |f| %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description' %>
  </div>

  <div class="form-group">
    <%= f.label :tags %><br>
    <%= f.text_field :tags, class: 'form-control', placeholder: 'graphic design, photoshop' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/folios/_form.html.erb
<%= form_for @folio do |f| %>
  <% if @folio.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p><b>Whoops.</b> Looks like there were some issues with your request</p>
      <ul>
        <% @folio.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control', placeholder: 'Description' %>
  </div>

  <div class="form-group">
    <%= f.label :tags %><br>
    <%= f.text_field :tags, class: 'form-control', placeholder: 'graphic design, photoshop' %>
  </div>

  <div class="form-group">
    <%= f.submit submit_text, class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>

app/views/folios/edit.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="page-header">
      <h1>Edit Folio Info</h1>
    </div>

    <%= render 'form', submit_text: 'Save' %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/folios/index.html.erb
<div class="page-header">
  <h1>Browse Folios</h1>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table">
      <tr>
        <th>Folio Name</th>
        <th>Creator</th>
        <th>Tags</th>
      </tr>
      <% @folios.each do |folio| %>
      <tr>
        <td><%= link_to folio.name, folio %></td>
        <td><%= folio.user.name %></td>
        <td><%= render 'tags', tags: folio.tags %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/folios/new.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="page-header">
      <h1>Create a Folio</h1>
    </div>

    <%= render 'form' %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/folios/show.html.erb
<div class="page-header">
  <h1><%= @folio.name %></h1>
</div>

<div class="row">
  <div class="col-md-12 folio-button-bar">
    <% if @first_folio_page.nil? && current_user != @folio.user %>
      This folio has no pages.
    <% elsif @first_folio_page.nil? %>
      <%= link_to 'Create First Page', new_folio_page_path(folio_id: @folio.id),
        class: 'btn btn-success' %>
    <% else %>
      <%= link_to 'Open Folio', @first_folio_page, class: 'btn btn-primary' %>
    <% end %>
    <% if current_user == @folio.user %>
      <%= link_to 'Edit Info', edit_folio_path, class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h4>Description</h4>
    <p class="lead">
      <%= @folio.description %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h4>Tags</h4>
    <%= render 'tags', tags: @folio.tags %>
  </div>
  <div class="col-md-6">
    <h4>About the Author</h4>
    <img src="<%= @folio.user.image %>" alt="User display photo" class="img-rounded folio-user-image">
    <h3><%= link_to @folio.user.name, @folio.user %></h3>
    <p><%= @folio.user.bio %></p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <hr>
    <h3>Comments</h3>

    <% if @folio.folio_comments.empty? %>
      <p><b>No comments here.</b> Say something nice...</p>
    <% else %>
      <% @folio.folio_comments.each do |comment| %>
        <%= render 'folio_comments/comment', comment: comment %>
      <% end %>
    <% end %>

    <% unless current_user.nil? %>
      <div class="well">
        <%= form_for :folio_comment, url: folio_comments_path do |f| %>
          <div class="form-group">
            <%= f.text_area :text, class: 'form-control', placeholder: 'y o u r  o p i n i o n s  h e r e' %>
          </div>

          <%= f.hidden_field :folio_id, value: @folio.id %>

          <div class="form-group">
            <%= f.submit 'Submit Comment', class: 'btn btn-primary btn-block' %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/images/_image.html.erb
<%= image_tag(image.image.url, class: 'uploaded-image') %>

app/views/images/edit.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="page-header">
      <h1>Edit Image</h1>
    </div>

    <h4>Current Image</h4>
    <div class="well">
      <% if @image.image.file.nil? %>
        <p><b>No image here at the moment...</b> Why not upload one?</p>
      <% else %>
        <%= render 'image', image: @image %>
      <% end %>
    </div>

    <%= form_for @image do |f| %>
      <% if @image.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p><b>Whoops.</b> Looks like there were some issues with your request</p>
          <ul>
            <% @image.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :image %><br>
        <%= f.file_field :image, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="page-header">
      <h1>Edit User Bio</h1>
    </div>


    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <p><b>Whoops.</b> Looks like there were some issues with your request</p>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :bio %><br>
        <%= f.text_area :bio, class: 'form-control', placeholder: 'Bio' %>
      </div>

      <div class="form-group">
        <%= f.submit 'Save', class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-3"></div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag(@user.image, class: 'user-profile-image') %>
    <hr>
    <h2><%= @user.name %></h2>
    <p><%= @user.bio %></p>
    <% if current_user == @user %>
      <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
  <div class="col-md-9">
    <h3>Folios</h3>
    <table class="table">
      <tr>
        <th>Folio Name</th>
        <th>Tags</th>
      </tr>
      <% @user.folios.each do |folio| %>
      <tr>
        <td><%= link_to folio.name, folio %></td>
        <td><%= render 'tags', tags: folio.tags %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>